
in:
  type: zendesk
  login_url: ${secret:zendesk.login_url}
  auth_method: token
  username: ${secret:zendesk.username}
  token: ${secret:zendesk.token}
  target: tickets
  start_time: ${start_time}
  columns:
  - {name: assignee_id, type: long}
  ......
filters: []
out: {}
exec: {}
