target_db: blogposts

job_priority: -1

# RandomForest
rf_seed: 71
rf_trees: 15
rf_num_train_parallel: 4
rf_max_depth: 30
min_split: 3
min_samples_leaf: 1

# over/down sampling
min_class_weight: 0.8
max_class_weight: 4.0

# heuristic calibration
f15_factor: 1.0
f20_factor: 1.0
f25_factor: 1.0
f35_factor: 1.0
f50_factor: 1.0
m15_factor: 1.0
m20_factor: 1.0
m25_factor: 1.0
m35_factor: 1.0
m50_factor: 1.0
